image: python:3.9

before_script:
  - python --version # For debugging
  - pip install isort pylint pytest pyqt6 db-sqlite3 requests bcrypt

stages:
  - linting
  - test

isort:
  stage: linting
  script:
    - python -m isort . --check-only

pylint:
  stage: linting
  script:
    - python -m pylint src

pytest:
  stage: test
  tags:
    - rpl
  script:
    - pytest
  only:
    - merge_request
